// <auto-generated />
using EstoqueService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstoqueService.Migrations
{
    [DbContext(typeof(EstoqueServiceContext))]
    [Migration("20201212131435_DB_V1")]
    partial class DB_V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("EstoqueService.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Codigo", "Nome")
                        .IsUnique();

                    b.ToTable("Produtos");

                    b.HasCheckConstraint("CK_Produtos_Quantidade", "[Quantidade] >=0");

                    b.HasCheckConstraint("CK_Produtos_Preco", "[Preco] >=0");
                });
#pragma warning restore 612, 618
        }
    }
}
